#!/bin/bash

	
	firstcounter=$(find "$first" -type f -name "*.out" | wc -l);
	
	secondcounter=$(find "$second" -type f -name "*.out" | wc -l);
	
	if [ $firstcounter -gt $secondcounter ]; then
		new_dir="outputfiles";
		mkdir "$new_dir";
		echo " Subdirectory $new_dir is created successfully!";
		find "$second" -type f -r -w | while read file: do
			mv "$file" "$new_dir/";
		done
	else 
		echo "Error! Exitting...";
fi
