#!/bin/bash

read -p "Enter 1st directory: " first;
read -p "Enter 2nd directory: " second;

if [ -d "$first" -a -d "$second" ]; then

        firstcounter=$(find "$first" -type f -name "*.c" | wc -l);

        secondcounter=$(find "$second" -type f -name "*.c" | wc -l);

        if [ %(($firstcounter + $secondcounter)) -gt 20 ]; then
                new_file="Cfile";
                mk -p -r "$new_file";
		$new_file < $(find "$first" -type f -name "*.c" -a find "$second" -type f -name "*.c");
                echo "File $new_file is created successfully!";
     	else
                echo "Total number of these files $(($firstcounter + $secondcounter)) is less than 20!. Exitting...";
        fi
else
        echo"Error! Exitting...";
fi
